site_name: "RHDH Docs Team Documentation"
site_description: "Documentation for Red Hat Developer Hub Docs Team"
site_url: "https://devhub.corp.redhat.com/catalog/default/component/rhdh-team-docs/docs"

plugins:
  - techdocs-core

nav:
  - Home: index.md
